### ISSUE TITLE
Deploy Pachyderm onto a Known IP

### ISSUE THREAD

**Issue by jpoon** [jpoon/aurora_deploy#12]
Maybe this will help: http://kubernetes.io/docs/user-guide/services/#choosing-your-own-ip-address

**Comment by jpoon** [comment]
- Pachyderm deployed inside Kubernetes subnet and using NodePort to expose 30650 and 30651
- The only known IP in k8s cluster is the master (10.0.1.100) we can use that to talk to pachyderm but it's not a good HA solution as the master can go down

Ideas:
- expose kube-dns outside the cluster to resolve pachd (https://stackoverflow.com/questions/37449121/how-to-expose-kube-dns-service-for-queries-outside-cluster)

**Comment by JonathanFraser** [comment]
The load balancer can be autocreated by kubernetes simply by setting the service to type "LoadBalancer" however this will by default provision a load balancer with a public facing endpoint.

If there was a way to route the cluster network into the outside world then we could use kube-dns or static clusterIP.

**Comment by JonathanFraser** [comment]
Apparently as of 1.2, nodes act as gateway to the cluster subnet, this means so long as the azure vnet route table is maintaining each node as a possible gateway then we can just use the ClusterIP as a destination.

**Comment by jpoon** [comment]
@JonathanFraser Each Kubernetes node maintains an iptable to help it resolve the ClusterIP and/or KubeDNS. As such, we'll need to use one of the nodes as a gateway. This is what we are doing at the moment as we have hard-coded the location of the master node and using that to communicate to Pachyderm.

However, if the master node goes down, we won't be able to communicate to Pachyderm. For this reason, I am proposing creating an internally facing load balancer with the Kubernetes agents in the backend pool. In this manner, if one of the agent's dies, the load balancer can still redirect the request to another agent.

**Comment by JonathanFraser** [comment]
There are three possible ways to communicate with a service in a kubernetes cluster. 

1) Have your client service specify the internal clusterIP of the service directly. This relys on having a route table in either your client node or the Vnet's default gateway which understands kubernetes and has route entries to the various nodes. 

2) expose the service as a node port and have the client specify the IP any kubernetes node. This is the method we are currently using. The IP we are specifying is the master node as in our deployment the master is considered a non-scheduable worker.

3) Expose the service as a load-balancer and have the client connect to the provisioned azure load balancer. This balancer sprays all the workers.

If I look into the Vnet definition for Azure there is some top level route entries for the cluster addresses. If the these route entries are being appropriately maintained and functional then the client should be able to specify the ClusterIP directly, whats more is that when you create a service you can specify it's ClusterIP instead of it being dynamically generated.

**Comment by JonathanFraser** [comment]
I'm going to add that there is a subtle difference between 1 and 2 and that is whether the kubernetes node is acting as a layer 3 vs layer 4 device respectively. In option 1 the client directly specifies the ClusterIP directly and the kubernetes node is a simple router. 
In Option 2 the client has to specify one of the nodes and it acts as a NAT with port forwarding enabled.
