### ISSUE TITLE
Unable to Delete Service Principal Through Portal

### ISSUE THREAD

**Issue by jpoon** [jpoon/aurora_deploy#3]
After including creation of SP through the script with https://github.com/jpoon/aurora_deploy/commit/edda9a2523b2db816b544b34b5c72af5cd1ae8a8, @JonathanFraser is now unable to delete the app through the portal. The delete button is grayed out.

**Comment by JonathanFraser** [comment]
Looks like this is related to all the guest account issues earlier. When I claimed ownership of one of our domains in AAD and then gave a new user in that domain permissions they were able to perform the delete correctly. I suspect the issue is just that there was no AAD with ownership of generalfusion.com and as such caused and issue with permissions.

**Comment by jpoon** [comment]
Alright. Closing out this issue.
